<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Add_Player.aspx.cs" Inherits="Employee.Account.Player.Add_Player" %>
<%@ MasterType VirtualPath="~/Site.Master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <div class="media">
    <%--<div class="media-left media-middle">
      <img src="C:\Users\kapudi\Pictures\Sample Pictures\Desert.ipg" class="media-object" style="width:60px">
    </div>--%>
    <div class="media-body">     
        <center>
            <br /><br />
   <div style="height:100%;width:100%" class="panel panel-default" >
       <div class="panel panel-info">
       <div class="panel-heading"> <h3>Add Player</h3></div></div>
   
    
       <div class="panel-body">
       <table>
     <tr  style="height:100%;margin:10%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblPlayerName" Text="Player_Name:"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3" ID="txtPlayerName" CssClass="form-control">    </asp:TextBox></td>
         <td>
                    <asp:RequiredFieldValidator ID="rfvName" runat="server" ControlToValidate="txtPlayerName" Text="Please provide Player Name" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="revName" runat="server" ControlToValidate="txtPlayerName" ValidationExpression="[A-Z][a-z]+" Text="Must start with capital" ErrorMessage="Name should start with capital" ForeColor="Red" Display="Dynamic"></asp:RegularExpressionValidator>
                </td>
     </tr>
    <%--Player ID Part----autogenerated
         <tr style="height:100%;margin:20%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblPlayerId" Text="Player Id:"></asp:Label></td>
         <td><asp:TextBox runat="server"  class="col-xs-3" CssClass="form-control" ID="txteamname"></asp:TextBox></td>
     </tr>--%>
     <tr style="height:100%;margin:10%">
         <td style="width:40%"><asp:Label class="control-label col-sm-2" runat="server" ID="lblTeamName" Text="Team_Name:" style="left: 0px; top: 10px; width: 28%"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3"  CssClass="form-control" ID="txtTeamName"></asp:TextBox></td>
                   <td>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtTeamName" Text="Please provide Team Name" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="txtTeamName" ValidationExpression="[A-Z][a-z]+" Text="Must start with capital" ErrorMessage="TeamName should start with capital alphabet" ForeColor="Red" Display="Dynamic"></asp:RegularExpressionValidator>
                </td>
     </tr>
     <tr style="margin:10%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblAge" Text="Age:"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3" CssClass="form-control" ID="txtAge" TextMode="Number"></asp:TextBox></td>
          <td>
                    <asp:RequiredFieldValidator ID="rfvID" runat="server" ControlToValidate="txtAge" Text="Please provide Player Age" ErrorMessage="Player Age should be provided" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>&nbsp;&nbsp;
                    <asp:RangeValidator ID="rvID" runat="server" ControlToValidate="txtAge" Type="Integer" MinimumValue="18" MaximumValue="60" ErrorMessage="Player Age should be 18 to 60" ForeColor="Red" Display="Dynamic"></asp:RangeValidator>
                </td>
     </tr>
      <tr style="margin:10%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblBirthPlace" Text="Birth_Place:"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3" CssClass="form-control" ID="txtBirthPlace"></asp:TextBox></td>
            <td>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="txtBirthPlace" Text="Please provide Birth place" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ControlToValidate="txtBirthPlace" ValidationExpression="[A-Z][a-z]+" Text="Birth place starting with capital" ErrorMessage="Name should start with capital alphabet" ForeColor="Red" Display="Dynamic"></asp:RegularExpressionValidator>
                </td>
     </tr>
     <tr style="margin:10%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblRole" Text="Role:"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3" CssClass="form-control" ID="txtRole"></asp:TextBox></td>
          <td>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="txtRole" Text="Please provide Player Role" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator3" runat="server" ControlToValidate="txtRole" ValidationExpression="[A-Z][a-z]+" Text="Player Role starting with capital" ErrorMessage="Player Role should start with capital" ForeColor="Red" Display="Dynamic"></asp:RegularExpressionValidator>
                </td>
     </tr>
     <tr style="margin:10%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblBattingStyle" Text="Batting_Style:"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3" CssClass="form-control" ID="txtBattingStyle"></asp:TextBox></td>
         <td>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="txtBattingStyle" Text="Please provide Batting Style" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator4" runat="server" ControlToValidate="txtBattingStyle" ValidationExpression="[A-Z][a-z]+"  ErrorMessage="Batting Style should start with capital" ForeColor="Red" Display="Dynamic"></asp:RegularExpressionValidator>
                </td>
     </tr>
     <tr style="margin:10%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblBowlingStyle" Text="Bowling_Style:"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3" CssClass="form-control" ID="txtBowlingStyle"></asp:TextBox></td>
          <td>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="txtBowlingStyle" Text="Please provide Bowling Style" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
                     <asp:RegularExpressionValidator ID="RegularExpressionValidator5" runat="server" ControlToValidate="txtBowlingStyle" ValidationExpression="[A-Z][a-z]+"  ErrorMessage="BowlingStyle should start with capital" ForeColor="Red" Display="Dynamic"></asp:RegularExpressionValidator>
                </td>
     </tr>
     <tr style="margin:10%">
         <td><asp:Label runat="server" class="control-label col-sm-2" ID="lblProfile" Text="Profile:"></asp:Label></td>
         <td><asp:TextBox runat="server" class="col-xs-3" CssClass="form-control" ID="txtProfile" TextMode="MultiLine" Rows="8" Columns="60"></asp:TextBox></td>
          <td>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ControlToValidate="txtProfile" Text="Please provide Profile" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>
     </td>
              </tr>
     <tr><td><br /></td></tr>
     <tr>
       <td></td>
         <td style="margin:100%"><asp:Button runat="server" class="btn btn-primary"  Text="Insert"/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
             
         <asp:Button runat="server"   class="btn btn-primary" Text="Reset" /></td>
     </tr>
 </table>
   </div>
    
    </div>
    

            </center>
          </div>
  </div>
</asp:Content>
